server:
  port: 80

spring:
  application:
    name: cloud_consumer-order
  cloud:
    consul:
      host: 192.168.0.109
      port: 8500
      discovery:
        service-name: ${spring.application.name}
